# Site settings
title: Action Marketing
email: thomas@onlyaction.com
description: > # this means to ignore newlines until "baseurl:"
  Full service automotive marketing firm. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jdmurphree
github_username:  onlyaction

# Build settings
markdown: kramdown
